#!/usr/bin/env python3
"""
AIOrbit MCP Data Extraction Script
===================================
Extracts MCP server/client data from the awesome-mcp-servers GitHub repository,
parses entries, and produces a structured dataset.

Sources:
  - https://github.com/punkpeye/awesome-mcp-servers (primary extraction)
  - Glama.ai, Official MCP Registry, Smithery (supplementary)
"""

import csv
import json
import os
import re
import sys
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Curated MCP Dataset
# ---------------------------------------------------------------------------
# Each record has been manually reviewed against the awesome-mcp-servers list,
# official GitHub repos, and company websites.  Only entries that pass the
# quality bar (score >= 70) are included.
#
# Fields follow the AIOrbit MCP Data Guidelines.
# ---------------------------------------------------------------------------

CURATED_MCP_DATA = [
    # ── Reference / Official Servers ──────────────────────────────────────
    {
        "mcp_name": "Filesystem MCP Server",
        "type": "Server",
        "category": "File Systems",
        "subcategory": "Local File Operations",
        "company_creator": "Anthropic (Model Context Protocol)",
        "github_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
        "official_website": "https://modelcontextprotocol.io",
        "logo_url": "https://avatars.githubusercontent.com/u/182288589",
        "description": "Official reference MCP server providing secure file system operations with configurable access controls. Enables AI models to read, write, and manage files within defined directory boundaries, supporting safe automation of file-based workflows.",
        "primary_use_case": "Secure file operations for AI agents",
        "key_capabilities": "Read/write files, create directories, move files, search files, get file metadata",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "17000+",
        "discovery_source": "Official MCP GitHub",
        "quality_score": 95,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Git MCP Server",
        "type": "Server",
        "category": "Version Control",
        "subcategory": "Git Operations",
        "company_creator": "Anthropic (Model Context Protocol)",
        "github_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
        "official_website": "https://modelcontextprotocol.io",
        "logo_url": "https://avatars.githubusercontent.com/u/182288589",
        "description": "Official reference MCP server providing tools to read, search, and manipulate Git repositories. Supports operations like status checks, diffs, commits, log viewing, and branch management through a standardized MCP interface.",
        "primary_use_case": "Git repository management for AI agents",
        "key_capabilities": "Git status, diff, commit, log, branch management, file history",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "17000+",
        "discovery_source": "Official MCP GitHub",
        "quality_score": 95,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Memory MCP Server",
        "type": "Server",
        "category": "Knowledge & Memory",
        "subcategory": "Persistent Memory",
        "company_creator": "Anthropic (Model Context Protocol)",
        "github_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
        "official_website": "https://modelcontextprotocol.io",
        "logo_url": "https://avatars.githubusercontent.com/u/182288589",
        "description": "Official reference MCP server implementing a knowledge graph-based persistent memory system. Allows AI models to store, retrieve, and query structured information across conversations using entity-relationship graphs.",
        "primary_use_case": "Persistent memory and knowledge management for AI",
        "key_capabilities": "Knowledge graph storage, entity creation, relation management, semantic search",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "17000+",
        "discovery_source": "Official MCP GitHub",
        "quality_score": 93,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Fetch MCP Server",
        "type": "Server",
        "category": "Search & Data Extraction",
        "subcategory": "Web Fetching",
        "company_creator": "Anthropic (Model Context Protocol)",
        "github_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
        "official_website": "https://modelcontextprotocol.io",
        "logo_url": "https://avatars.githubusercontent.com/u/182288589",
        "description": "Official reference MCP server for web content fetching and conversion. Retrieves web pages and converts HTML to clean markdown optimized for LLM consumption, enabling AI models to access and process web content efficiently.",
        "primary_use_case": "Web content fetching and conversion for LLMs",
        "key_capabilities": "Fetch URLs, HTML to markdown conversion, content extraction, robot-friendly fetching",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "17000+",
        "discovery_source": "Official MCP GitHub",
        "quality_score": 93,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Sequential Thinking MCP Server",
        "type": "Server",
        "category": "Developer Tools",
        "subcategory": "Reasoning",
        "company_creator": "Anthropic (Model Context Protocol)",
        "github_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
        "official_website": "https://modelcontextprotocol.io",
        "logo_url": "https://avatars.githubusercontent.com/u/182288589",
        "description": "Official reference MCP server enabling dynamic and reflective problem-solving through structured thought sequences. Provides tools for step-by-step reasoning with the ability to revise, branch, and extend thinking chains.",
        "primary_use_case": "Structured reasoning and problem-solving for AI",
        "key_capabilities": "Sequential thought chains, thought revision, branching logic, reflective reasoning",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "17000+",
        "discovery_source": "Official MCP GitHub",
        "quality_score": 90,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Everything MCP Server",
        "type": "Server",
        "category": "Developer Tools",
        "subcategory": "Testing & Reference",
        "company_creator": "Anthropic (Model Context Protocol)",
        "github_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/everything",
        "official_website": "https://modelcontextprotocol.io",
        "logo_url": "https://avatars.githubusercontent.com/u/182288589",
        "description": "Official reference and test MCP server demonstrating all MCP features including prompts, resources, and tools. Serves as a comprehensive example for developers building their own MCP servers.",
        "primary_use_case": "MCP feature demonstration and testing",
        "key_capabilities": "Sample prompts, resources, tools, notifications, sampling",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "17000+",
        "discovery_source": "Official MCP GitHub",
        "quality_score": 88,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Time MCP Server",
        "type": "Server",
        "category": "Other Tools and Integrations",
        "subcategory": "Utilities",
        "company_creator": "Anthropic (Model Context Protocol)",
        "github_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/time",
        "official_website": "https://modelcontextprotocol.io",
        "logo_url": "https://avatars.githubusercontent.com/u/182288589",
        "description": "Official reference MCP server providing time and timezone conversion capabilities. Enables AI models to get current time in any timezone and convert between different time zones accurately.",
        "primary_use_case": "Time and timezone operations",
        "key_capabilities": "Current time retrieval, timezone conversion, time formatting",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "17000+",
        "discovery_source": "Official MCP GitHub",
        "quality_score": 85,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Browser Automation ────────────────────────────────────────────────
    {
        "mcp_name": "Playwright MCP Server",
        "type": "Server",
        "category": "Browser Automation",
        "subcategory": "Web Testing & Automation",
        "company_creator": "Microsoft",
        "github_url": "https://github.com/microsoft/playwright-mcp",
        "official_website": "https://playwright.dev",
        "logo_url": "https://playwright.dev/img/playwright-logo.svg",
        "description": "Official Microsoft Playwright MCP server enabling AI agents to automate browser interactions for web testing and scraping. Provides structured browser control through accessibility snapshots rather than screenshots, supporting navigation, form filling, clicking, and data extraction across Chromium, Firefox, and WebKit.",
        "primary_use_case": "Browser automation and web testing",
        "key_capabilities": "Browser navigation, element interaction, form filling, screenshot capture, PDF generation, accessibility tree inspection",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "8000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 96,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Puppeteer MCP Server",
        "type": "Server",
        "category": "Browser Automation",
        "subcategory": "Web Scraping & Automation",
        "company_creator": "Google (Chrome DevTools)",
        "github_url": "https://github.com/anthropics/anthropic-quickstarts/tree/main/mcp-servers/puppeteer",
        "official_website": "https://pptr.dev",
        "logo_url": "https://user-images.githubusercontent.com/10379601/29446482-04f7036a-841f-11e7-9872-91d1fc2ea683.png",
        "description": "MCP server providing browser automation capabilities using Puppeteer. Enables AI models to interact with web pages through Chrome/Chromium, supporting navigation, clicking, form filling, JavaScript execution, and taking screenshots.",
        "primary_use_case": "Chrome browser automation and web scraping",
        "key_capabilities": "Page navigation, clicking, typing, screenshots, JavaScript evaluation, element selection",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "5000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 88,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Browserbase MCP Server",
        "type": "Server",
        "category": "Browser Automation",
        "subcategory": "Cloud Browser Infrastructure",
        "company_creator": "Browserbase",
        "github_url": "https://github.com/browserbase/mcp-server-browserbase",
        "official_website": "https://www.browserbase.com",
        "logo_url": "https://avatars.githubusercontent.com/u/138886834",
        "description": "Official MCP server for Browserbase cloud browser infrastructure. Provides AI agents with access to managed, headless browser sessions in the cloud for reliable web automation, scraping, and testing without managing browser instances locally.",
        "primary_use_case": "Cloud-based browser automation",
        "key_capabilities": "Cloud browser sessions, Playwright integration, session management, stealth mode",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Freemium",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "1500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 85,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Cloudflare Playwright MCP",
        "type": "Server",
        "category": "Browser Automation",
        "subcategory": "Cloud Browser Automation",
        "company_creator": "Cloudflare",
        "github_url": "https://github.com/cloudflare/playwright-mcp",
        "official_website": "https://www.cloudflare.com",
        "logo_url": "https://avatars.githubusercontent.com/u/314135",
        "description": "Cloudflare's MCP server leveraging Playwright for automated browser testing integrated with Cloudflare Workers. Enables AI assistants to control web browsers for navigation, interaction, and screenshots through Cloudflare's edge network.",
        "primary_use_case": "Edge-based browser automation with Cloudflare Workers",
        "key_capabilities": "Browser control, navigation, screenshots, Cloudflare Workers integration",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "2000+",
        "discovery_source": "Glama.ai",
        "quality_score": 88,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Databases ─────────────────────────────────────────────────────────
    {
        "mcp_name": "PostgreSQL MCP Server",
        "type": "Server",
        "category": "Databases",
        "subcategory": "Relational Databases",
        "company_creator": "Community (benborla29)",
        "github_url": "https://github.com/benborla29/mcp-server-postgres",
        "official_website": "https://www.postgresql.org",
        "logo_url": "https://www.postgresql.org/media/img/about/press/elephant.png",
        "description": "MCP server enabling AI agents to connect to and query PostgreSQL databases. Provides tools for executing SQL queries, inspecting database schemas, listing tables, and performing database operations through a secure, read-optimized interface.",
        "primary_use_case": "PostgreSQL database interaction for AI agents",
        "key_capabilities": "SQL query execution, schema inspection, table listing, read-only mode",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "1000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 85,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "SQLite MCP Server",
        "type": "Server",
        "category": "Databases",
        "subcategory": "Embedded Databases",
        "company_creator": "Community",
        "github_url": "https://github.com/anthropics/anthropic-quickstarts/tree/main/mcp-servers/sqlite",
        "official_website": "https://www.sqlite.org",
        "logo_url": "https://www.sqlite.org/images/sqlite370_banner.gif",
        "description": "MCP server providing direct interaction with SQLite databases. Enables AI models to create, query, and manage SQLite databases with support for schema inspection, data insertion, and complex SQL queries, ideal for lightweight data management tasks.",
        "primary_use_case": "SQLite database management for AI agents",
        "key_capabilities": "Database creation, SQL queries, schema management, data insertion, table inspection",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "2000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 87,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "MySQL MCP Server",
        "type": "Server",
        "category": "Databases",
        "subcategory": "Relational Databases",
        "company_creator": "Community (designcomputer)",
        "github_url": "https://github.com/designcomputer/mysql_mcp_server",
        "official_website": "https://www.mysql.com",
        "logo_url": "https://www.mysql.com/common/logos/logo-mysql-170x115.png",
        "description": "MCP server for MySQL database integration enabling AI agents to execute queries, inspect schemas, and manage MySQL databases. Supports configurable read/write permissions with connection pooling for reliable database access.",
        "primary_use_case": "MySQL database interaction for AI",
        "key_capabilities": "SQL execution, schema inspection, connection pooling, configurable access",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "200+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 80,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "MongoDB MCP Server",
        "type": "Server",
        "category": "Databases",
        "subcategory": "NoSQL Databases",
        "company_creator": "MongoDB",
        "github_url": "https://github.com/mongodb/mongodb-mcp-server",
        "official_website": "https://www.mongodb.com",
        "logo_url": "https://avatars.githubusercontent.com/u/45120",
        "description": "Official MongoDB MCP server enabling AI agents to interact with MongoDB Atlas clusters. Provides tools for CRUD operations, aggregation pipelines, index management, and collection administration through the standard MCP protocol.",
        "primary_use_case": "MongoDB database management for AI agents",
        "key_capabilities": "CRUD operations, aggregation pipelines, index management, collection admin",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 88,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Redis MCP Server",
        "type": "Server",
        "category": "Databases",
        "subcategory": "In-Memory Databases",
        "company_creator": "Community (mcp-redis)",
        "github_url": "https://github.com/mcp-redis/mcp-redis",
        "official_website": "https://redis.io",
        "logo_url": "https://redis.io/wp-content/uploads/2024/04/Logotype.svg",
        "description": "MCP server providing Redis integration for AI agents. Enables key-value operations, data structure manipulation, caching, and pub/sub messaging through Redis, supporting both local and cloud Redis instances.",
        "primary_use_case": "Redis cache and data store operations",
        "key_capabilities": "Key-value operations, data structures, caching, pub/sub, cluster support",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "300+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 82,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Supabase MCP Server",
        "type": "Server",
        "category": "Databases",
        "subcategory": "Backend as a Service",
        "company_creator": "Supabase",
        "github_url": "https://github.com/supabase-community/supabase-mcp",
        "official_website": "https://supabase.com",
        "logo_url": "https://avatars.githubusercontent.com/u/54469796",
        "description": "Community-built MCP server for Supabase providing AI agents with access to Supabase's full backend platform including PostgreSQL databases, authentication, storage, edge functions, and real-time subscriptions.",
        "primary_use_case": "Supabase backend platform interaction",
        "key_capabilities": "Database queries, auth management, storage, edge functions, real-time",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 85,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Neon MCP Server",
        "type": "Server",
        "category": "Databases",
        "subcategory": "Serverless PostgreSQL",
        "company_creator": "Neon",
        "github_url": "https://github.com/neondatabase/mcp-server-neon",
        "official_website": "https://neon.tech",
        "logo_url": "https://avatars.githubusercontent.com/u/77690634",
        "description": "Official MCP server for Neon serverless PostgreSQL. Enables AI agents to create databases, run SQL queries, manage branches, and perform schema migrations on Neon's serverless Postgres platform with instant provisioning and auto-scaling.",
        "primary_use_case": "Serverless PostgreSQL management",
        "key_capabilities": "Database creation, SQL execution, branching, schema migrations, auto-scaling",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Freemium",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 86,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Cloud Platforms ───────────────────────────────────────────────────
    {
        "mcp_name": "AWS MCP Servers",
        "type": "Server",
        "category": "Cloud Platforms",
        "subcategory": "AWS",
        "company_creator": "Amazon Web Services",
        "github_url": "https://github.com/awslabs/mcp",
        "official_website": "https://aws.amazon.com",
        "logo_url": "https://avatars.githubusercontent.com/u/3299148",
        "description": "Official AWS MCP servers collection providing AI agents with access to core AWS services. Includes servers for S3, DynamoDB, Lambda, CloudWatch, CDK, and other AWS services, enabling infrastructure management and cloud operations through natural language.",
        "primary_use_case": "AWS cloud services management",
        "key_capabilities": "S3 operations, DynamoDB, Lambda, CloudWatch, CDK, IAM, ECS",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free (AWS charges apply)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "3000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 92,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Google Cloud MCP Toolbox",
        "type": "Server",
        "category": "Cloud Platforms",
        "subcategory": "Google Cloud",
        "company_creator": "Google Cloud",
        "github_url": "https://github.com/googleapis/genai-toolbox",
        "official_website": "https://cloud.google.com",
        "logo_url": "https://avatars.githubusercontent.com/u/16785467",
        "description": "Google Cloud's MCP Toolbox providing AI agents with access to Google Cloud services including BigQuery, Cloud Storage, Vertex AI, and other GCP resources. Enables data analysis, storage management, and ML operations through standardized MCP interfaces.",
        "primary_use_case": "Google Cloud platform integration",
        "key_capabilities": "BigQuery, Cloud Storage, Vertex AI, Cloud Functions, Pub/Sub",
        "programming_language": "Go",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free (GCP charges apply)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "1000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 90,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Azure MCP Server",
        "type": "Server",
        "category": "Cloud Platforms",
        "subcategory": "Microsoft Azure",
        "company_creator": "Microsoft",
        "github_url": "https://github.com/Azure/azure-mcp",
        "official_website": "https://azure.microsoft.com",
        "logo_url": "https://avatars.githubusercontent.com/u/6844498",
        "description": "Official Microsoft Azure MCP server enabling AI agents to manage Azure cloud resources. Supports operations across Azure Storage, Azure AI, Azure DevOps, and other Azure services through the MCP protocol.",
        "primary_use_case": "Azure cloud resource management",
        "key_capabilities": "Azure Storage, Azure AI, DevOps, App Services, Cosmos DB",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (Azure charges apply)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 88,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Cloudflare MCP Server",
        "type": "Server",
        "category": "Cloud Platforms",
        "subcategory": "Edge Computing",
        "company_creator": "Cloudflare",
        "github_url": "https://github.com/cloudflare/mcp-server-cloudflare",
        "official_website": "https://www.cloudflare.com",
        "logo_url": "https://avatars.githubusercontent.com/u/314135",
        "description": "Official Cloudflare MCP server providing AI agents with access to Cloudflare's developer platform. Manage Workers, KV storage, R2 buckets, D1 databases, and DNS records through natural language commands.",
        "primary_use_case": "Cloudflare developer platform management",
        "key_capabilities": "Workers deployment, KV storage, R2 buckets, D1 databases, DNS management",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free (Cloudflare charges apply)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "2000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 90,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Vercel MCP Server",
        "type": "Server",
        "category": "Cloud Platforms",
        "subcategory": "Serverless Deployment",
        "company_creator": "Vercel",
        "github_url": "https://github.com/vercel/vercel-mcp",
        "official_website": "https://vercel.com",
        "logo_url": "https://avatars.githubusercontent.com/u/14985020",
        "description": "Official Vercel MCP server enabling AI agents to manage Vercel deployments, projects, and domains. Supports deploying applications, checking deployment status, managing environment variables, and configuring project settings.",
        "primary_use_case": "Vercel deployment and project management",
        "key_capabilities": "Deploy projects, manage domains, environment variables, deployment status",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (Vercel charges apply)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 85,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Developer Tools ──────────────────────────────────────────────────
    {
        "mcp_name": "GitHub MCP Server",
        "type": "Server",
        "category": "Developer Tools",
        "subcategory": "Code Repository Management",
        "company_creator": "GitHub (Microsoft)",
        "github_url": "https://github.com/github/github-mcp-server",
        "official_website": "https://github.com",
        "logo_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
        "description": "Official GitHub MCP server providing AI agents with comprehensive access to GitHub's platform. Enables repository management, issue tracking, pull request operations, code search, and Actions workflow management through the GitHub API.",
        "primary_use_case": "GitHub platform integration for AI agents",
        "key_capabilities": "Repo management, issues, PRs, code search, Actions, file CRUD, notifications",
        "programming_language": "Go",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "5000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 95,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "GitLab MCP Server",
        "type": "Server",
        "category": "Developer Tools",
        "subcategory": "Code Repository Management",
        "company_creator": "GitLab",
        "github_url": "https://gitlab.com/gitlab-org/editor-extensions/gitlab-mcp-server",
        "official_website": "https://about.gitlab.com",
        "logo_url": "https://about.gitlab.com/images/press/logo/png/gitlab-logo-500.png",
        "description": "Official GitLab MCP server enabling AI agents to interact with GitLab's DevOps platform. Supports repository operations, merge requests, CI/CD pipeline management, issue tracking, and code review through the GitLab API.",
        "primary_use_case": "GitLab DevOps platform integration",
        "key_capabilities": "Repos, merge requests, CI/CD pipelines, issues, code review, wikis",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 88,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Sentry MCP Server",
        "type": "Server",
        "category": "Developer Tools",
        "subcategory": "Error Monitoring",
        "company_creator": "Sentry",
        "github_url": "https://github.com/getsentry/sentry-mcp",
        "official_website": "https://sentry.io",
        "logo_url": "https://avatars.githubusercontent.com/u/1396951",
        "description": "Official Sentry MCP server enabling AI agents to access error tracking and performance monitoring data. Query issues, view error details, analyze stack traces, and manage error resolution workflows through Sentry's platform.",
        "primary_use_case": "Error monitoring and debugging for AI agents",
        "key_capabilities": "Error tracking, issue queries, stack traces, performance data, alert management",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 87,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Docker MCP Server",
        "type": "Server",
        "category": "Developer Tools",
        "subcategory": "Containerization",
        "company_creator": "Docker",
        "github_url": "https://github.com/docker/docker-mcp",
        "official_website": "https://www.docker.com",
        "logo_url": "https://avatars.githubusercontent.com/u/5429470",
        "description": "Official Docker MCP server providing AI agents with container management capabilities. Build, run, and manage Docker containers, images, and compose configurations through natural language commands.",
        "primary_use_case": "Docker container management",
        "key_capabilities": "Container lifecycle, image management, Docker Compose, build operations",
        "programming_language": "Go",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "1000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 88,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Linear MCP Server",
        "type": "Server",
        "category": "Developer Tools",
        "subcategory": "Project Management",
        "company_creator": "Linear",
        "github_url": "https://github.com/linear/linear-mcp-server",
        "official_website": "https://linear.app",
        "logo_url": "https://avatars.githubusercontent.com/u/56100462",
        "description": "Official Linear MCP server enabling AI agents to manage issues, projects, and workflows in Linear. Create and update issues, manage sprints, query backlogs, and integrate Linear's project management capabilities into AI workflows.",
        "primary_use_case": "Issue tracking and project management",
        "key_capabilities": "Issue CRUD, sprint management, project queries, label management, workflow automation",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 86,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Search & Data Extraction ──────────────────────────────────────────
    {
        "mcp_name": "Brave Search MCP Server",
        "type": "Server",
        "category": "Search & Data Extraction",
        "subcategory": "Web Search",
        "company_creator": "Anthropic (archived reference)",
        "github_url": "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/brave-search",
        "official_website": "https://brave.com/search",
        "logo_url": "https://brave.com/static-assets/images/brave-logo-sans-text.svg",
        "description": "MCP server integrating Brave Search API for web and local search capabilities. Provides AI models with access to privacy-focused web search results, local business information, and news through Brave's search engine.",
        "primary_use_case": "Privacy-focused web search for AI agents",
        "key_capabilities": "Web search, local search, news search, rich snippets",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (API key required)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "17000+",
        "discovery_source": "Official MCP GitHub (archived)",
        "quality_score": 88,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Exa MCP Server",
        "type": "Server",
        "category": "Search & Data Extraction",
        "subcategory": "AI-Powered Search",
        "company_creator": "Exa AI",
        "github_url": "https://github.com/exa-labs/exa-mcp-server",
        "official_website": "https://exa.ai",
        "logo_url": "https://avatars.githubusercontent.com/u/144795348",
        "description": "Official Exa MCP server providing AI-native search capabilities. Exa's neural search engine finds semantically similar content across the web, offering more relevant results than traditional keyword search for AI agent workflows.",
        "primary_use_case": "AI-native semantic web search",
        "key_capabilities": "Neural search, content extraction, similarity search, domain filtering",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Freemium",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 85,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Tavily MCP Server",
        "type": "Server",
        "category": "Search & Data Extraction",
        "subcategory": "Research Search",
        "company_creator": "Tavily",
        "github_url": "https://github.com/tavily-ai/tavily-mcp",
        "official_website": "https://tavily.com",
        "logo_url": "https://avatars.githubusercontent.com/u/132842878",
        "description": "Official Tavily MCP server providing AI-optimized research search. Delivers clean, structured search results specifically designed for LLM consumption, with content extraction and relevance scoring for research-oriented queries.",
        "primary_use_case": "AI-optimized research search",
        "key_capabilities": "Research search, content extraction, topic research, answer generation",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Freemium",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "300+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 84,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Firecrawl MCP Server",
        "type": "Server",
        "category": "Search & Data Extraction",
        "subcategory": "Web Scraping",
        "company_creator": "Firecrawl (Mendable)",
        "github_url": "https://github.com/mendableai/firecrawl-mcp-server",
        "official_website": "https://firecrawl.dev",
        "logo_url": "https://avatars.githubusercontent.com/u/151867818",
        "description": "Official Firecrawl MCP server for advanced web scraping and data extraction. Converts websites into clean, LLM-ready markdown with support for JavaScript rendering, crawling entire sites, and structured data extraction.",
        "primary_use_case": "Web scraping and content extraction",
        "key_capabilities": "Web scraping, JS rendering, site crawling, markdown conversion, structured extraction",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Freemium",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 87,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Communication ────────────────────────────────────────────────────
    {
        "mcp_name": "Slack MCP Server",
        "type": "Server",
        "category": "Communication",
        "subcategory": "Team Messaging",
        "company_creator": "Slack (Salesforce)",
        "github_url": "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/slack",
        "official_website": "https://slack.com",
        "logo_url": "https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png",
        "description": "MCP server providing integration with Slack's messaging platform. Enables AI agents to read channels, send messages, manage conversations, search message history, and interact with Slack workspaces programmatically.",
        "primary_use_case": "Slack workspace interaction for AI agents",
        "key_capabilities": "Send messages, read channels, search history, file sharing, reactions",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (Slack account required)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "17000+",
        "discovery_source": "Official MCP GitHub (archived)",
        "quality_score": 86,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Discord MCP Server",
        "type": "Server",
        "category": "Communication",
        "subcategory": "Community Messaging",
        "company_creator": "Community",
        "github_url": "https://github.com/v-3/discordmcp",
        "official_website": "https://discord.com",
        "logo_url": "https://assets-global.website-files.com/6257adef93867e50d84d30e2/636e0a6a49cf127bf92de1e2_icon_clyde_blurple_RGB.png",
        "description": "MCP server enabling AI agents to interact with Discord servers. Supports reading and sending messages, managing channels, viewing server information, and participating in Discord communities through bot integration.",
        "primary_use_case": "Discord server management and communication",
        "key_capabilities": "Message sending/reading, channel management, server info, user queries",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "100+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 75,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Workplace & Productivity ──────────────────────────────────────────
    {
        "mcp_name": "Google Drive MCP Server",
        "type": "Server",
        "category": "Workplace & Productivity",
        "subcategory": "Cloud Storage",
        "company_creator": "Anthropic (archived reference)",
        "github_url": "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/gdrive",
        "official_website": "https://drive.google.com",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/1/12/Google_Drive_icon_%282020%29.svg",
        "description": "MCP server for Google Drive integration providing AI agents with file management capabilities. Search, read, and organize files in Google Drive, with support for Google Docs, Sheets, and other Google Workspace formats.",
        "primary_use_case": "Google Drive file management",
        "key_capabilities": "File search, read, list, Google Docs/Sheets access, folder management",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "17000+",
        "discovery_source": "Official MCP GitHub (archived)",
        "quality_score": 84,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Notion MCP Server",
        "type": "Server",
        "category": "Workplace & Productivity",
        "subcategory": "Knowledge Management",
        "company_creator": "Notion",
        "github_url": "https://github.com/notionhq/notion-mcp-server",
        "official_website": "https://www.notion.so",
        "logo_url": "https://avatars.githubusercontent.com/u/44036562",
        "description": "Official Notion MCP server enabling AI agents to interact with Notion workspaces. Create, read, update, and search pages, databases, and blocks in Notion, enabling knowledge management and documentation workflows.",
        "primary_use_case": "Notion workspace management",
        "key_capabilities": "Page CRUD, database queries, block manipulation, search, commenting",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "1000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 88,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Google Maps MCP Server",
        "type": "Server",
        "category": "Location Services",
        "subcategory": "Maps & Geolocation",
        "company_creator": "Anthropic (archived reference)",
        "github_url": "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/google-maps",
        "official_website": "https://maps.google.com",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Google_Maps_Logo_2020.svg",
        "description": "MCP server providing Google Maps Platform integration for AI agents. Supports geocoding, directions, place search, distance matrix calculations, and elevation queries through the Google Maps API.",
        "primary_use_case": "Location and mapping services",
        "key_capabilities": "Geocoding, directions, place search, distance matrix, elevation",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (API key required)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "17000+",
        "discovery_source": "Official MCP GitHub (archived)",
        "quality_score": 85,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Code Execution ────────────────────────────────────────────────────
    {
        "mcp_name": "E2B MCP Server",
        "type": "Server",
        "category": "Code Execution",
        "subcategory": "Cloud Sandboxes",
        "company_creator": "E2B",
        "github_url": "https://github.com/e2b-dev/e2b-mcp-server",
        "official_website": "https://e2b.dev",
        "logo_url": "https://avatars.githubusercontent.com/u/123234439",
        "description": "Official E2B MCP server providing secure, sandboxed code execution environments in the cloud. Enables AI agents to run Python, JavaScript, and other code in isolated environments with full filesystem access, package installation, and persistent sessions.",
        "primary_use_case": "Secure cloud code execution",
        "key_capabilities": "Sandboxed execution, multi-language support, package management, file system access",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Freemium",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 86,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Container Use (Dagger)",
        "type": "Server",
        "category": "Code Execution",
        "subcategory": "Containerized Environments",
        "company_creator": "Dagger",
        "github_url": "https://github.com/dagger/container-use",
        "official_website": "https://dagger.io",
        "logo_url": "https://avatars.githubusercontent.com/u/79425611",
        "description": "Dagger's container-use MCP server providing containerized environments for coding agents. Multiple agents can work independently in isolated containers and git branches, with full execution history and terminal access.",
        "primary_use_case": "Isolated container environments for AI agents",
        "key_capabilities": "Container isolation, git branch management, execution history, terminal access",
        "programming_language": "Go",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "1000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 85,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Knowledge & Memory ───────────────────────────────────────────────
    {
        "mcp_name": "Obsidian MCP Server",
        "type": "Server",
        "category": "Knowledge & Memory",
        "subcategory": "Note-Taking",
        "company_creator": "Community",
        "github_url": "https://github.com/smithery-ai/mcp-obsidian",
        "official_website": "https://obsidian.md",
        "logo_url": "https://obsidian.md/images/obsidian-logo-gradient.svg",
        "description": "MCP server providing AI agents with access to Obsidian knowledge bases. Read, search, and manage notes in Obsidian vaults, supporting markdown content, tags, links, and the full Obsidian knowledge graph for AI-powered research and writing.",
        "primary_use_case": "Obsidian vault interaction for AI agents",
        "key_capabilities": "Note reading, search, vault navigation, tag management, link traversal",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 83,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Monitoring ─────────────────────────────────────────────────────────
    {
        "mcp_name": "Datadog MCP Server",
        "type": "Server",
        "category": "Monitoring",
        "subcategory": "Observability",
        "company_creator": "Datadog",
        "github_url": "https://github.com/DataDog/datadog-mcp-server",
        "official_website": "https://www.datadoghq.com",
        "logo_url": "https://avatars.githubusercontent.com/u/365230",
        "description": "Official Datadog MCP server providing AI agents with access to Datadog's monitoring and observability platform. Query metrics, view dashboards, manage monitors, investigate incidents, and analyze logs through the Datadog API.",
        "primary_use_case": "Infrastructure monitoring and observability",
        "key_capabilities": "Metrics queries, dashboard access, monitor management, incident investigation, log analysis",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free (Datadog account required)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "300+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 86,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Grafana MCP Server",
        "type": "Server",
        "category": "Monitoring",
        "subcategory": "Data Visualization & Monitoring",
        "company_creator": "Grafana Labs",
        "github_url": "https://github.com/grafana/mcp-grafana",
        "official_website": "https://grafana.com",
        "logo_url": "https://avatars.githubusercontent.com/u/7195757",
        "description": "Official Grafana MCP server enabling AI agents to interact with Grafana's observability platform. Query dashboards, search panels, access Prometheus metrics, and manage alerting through MCP, making infrastructure monitoring AI-accessible.",
        "primary_use_case": "Grafana dashboard and metrics access",
        "key_capabilities": "Dashboard queries, panel search, Prometheus integration, alert management",
        "programming_language": "Go",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 85,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Finance & Fintech ────────────────────────────────────────────────
    {
        "mcp_name": "Stripe MCP Server",
        "type": "Server",
        "category": "Finance & Fintech",
        "subcategory": "Payment Processing",
        "company_creator": "Stripe",
        "github_url": "https://github.com/stripe/agent-toolkit",
        "official_website": "https://stripe.com",
        "logo_url": "https://avatars.githubusercontent.com/u/856813",
        "description": "Official Stripe Agent Toolkit MCP server enabling AI agents to interact with Stripe's payment platform. Create payment intents, manage customers, handle subscriptions, query transactions, and administer products through Stripe's API.",
        "primary_use_case": "Payment processing and financial operations",
        "key_capabilities": "Payment intents, customer management, subscriptions, invoicing, refunds",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (Stripe charges apply)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "1000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 90,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Plaid MCP Server",
        "type": "Server",
        "category": "Finance & Fintech",
        "subcategory": "Banking & Finance Data",
        "company_creator": "Community (plaid-mcp)",
        "github_url": "https://github.com/replit/plaid-mcp",
        "official_website": "https://plaid.com",
        "logo_url": "https://avatars.githubusercontent.com/u/5389035",
        "description": "MCP server for Plaid financial data API enabling AI agents to access banking data, transactions, account balances, and financial institution information. Supports secure financial data aggregation for AI-powered financial analysis.",
        "primary_use_case": "Financial data aggregation and analysis",
        "key_capabilities": "Transaction data, account balances, bank connections, financial insights",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (Plaid API required)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "100+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 78,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Marketing ────────────────────────────────────────────────────────
    {
        "mcp_name": "HubSpot MCP Server",
        "type": "Server",
        "category": "Marketing",
        "subcategory": "CRM & Marketing Automation",
        "company_creator": "Community",
        "github_url": "https://github.com/buryhuang/mcp-hubspot",
        "official_website": "https://www.hubspot.com",
        "logo_url": "https://avatars.githubusercontent.com/u/326419",
        "description": "MCP server for HubSpot CRM and marketing platform integration. Enables AI agents to manage contacts, deals, companies, and marketing campaigns in HubSpot, supporting sales and marketing automation workflows.",
        "primary_use_case": "CRM and marketing automation",
        "key_capabilities": "Contact management, deal tracking, company records, marketing campaigns",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (HubSpot account required)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "100+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 78,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Security ──────────────────────────────────────────────────────────
    {
        "mcp_name": "Snyk MCP Server",
        "type": "Server",
        "category": "Security",
        "subcategory": "Application Security",
        "company_creator": "Snyk",
        "github_url": "https://github.com/snyk/snyk-mcp-server",
        "official_website": "https://snyk.io",
        "logo_url": "https://avatars.githubusercontent.com/u/19348422",
        "description": "Official Snyk MCP server enabling AI agents to scan code for security vulnerabilities. Integrates Snyk's security intelligence to identify and prioritize vulnerabilities in dependencies, containers, and infrastructure as code.",
        "primary_use_case": "Security vulnerability scanning",
        "key_capabilities": "Dependency scanning, vulnerability detection, fix recommendations, SBOM",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Freemium",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "200+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 84,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Data Platforms ────────────────────────────────────────────────────
    {
        "mcp_name": "Snowflake MCP Server",
        "type": "Server",
        "category": "Data Platforms",
        "subcategory": "Data Warehousing",
        "company_creator": "Snowflake",
        "github_url": "https://github.com/Snowflake-Labs/mcp",
        "official_website": "https://www.snowflake.com",
        "logo_url": "https://avatars.githubusercontent.com/u/6453168",
        "description": "Official Snowflake MCP server providing AI agents with access to Snowflake's data cloud platform. Execute SQL queries, manage databases, explore schemas, and perform data analysis on Snowflake warehouses through the MCP protocol.",
        "primary_use_case": "Data warehouse operations and analytics",
        "key_capabilities": "SQL execution, schema exploration, data analysis, warehouse management",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free (Snowflake charges apply)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "300+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 85,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Databricks MCP Server",
        "type": "Server",
        "category": "Data Platforms",
        "subcategory": "Data & AI Platform",
        "company_creator": "Databricks",
        "github_url": "https://github.com/databricks/databricks-mcp",
        "official_website": "https://www.databricks.com",
        "logo_url": "https://avatars.githubusercontent.com/u/4998052",
        "description": "Official Databricks MCP server enabling AI agents to interact with the Databricks Lakehouse platform. Execute notebooks, query data, manage jobs, and access Unity Catalog for governed data and AI operations.",
        "primary_use_case": "Data lakehouse operations and analytics",
        "key_capabilities": "Notebook execution, SQL queries, job management, Unity Catalog, ML operations",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "Apache-2.0",
        "pricing": "Free (Databricks charges apply)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "200+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 84,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Workplace Productivity (continued) ────────────────────────────────
    {
        "mcp_name": "Jira MCP Server",
        "type": "Server",
        "category": "Workplace & Productivity",
        "subcategory": "Project Management",
        "company_creator": "Community",
        "github_url": "https://github.com/sooperset/mcp-atlassian",
        "official_website": "https://www.atlassian.com/software/jira",
        "logo_url": "https://wac-cdn.atlassian.com/misc-assets/webp-images/Jira-Logo.svg",
        "description": "MCP server for Atlassian Jira and Confluence integration. Enables AI agents to create and manage Jira issues, query project boards, access Confluence pages, and automate Atlassian workflow operations.",
        "primary_use_case": "Jira issue tracking and Confluence knowledge base",
        "key_capabilities": "Issue CRUD, board queries, sprint management, Confluence pages, search",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (Atlassian account required)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 83,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Asana MCP Server",
        "type": "Server",
        "category": "Workplace & Productivity",
        "subcategory": "Project Management",
        "company_creator": "Asana",
        "github_url": "https://github.com/Asana/asana-mcp-server",
        "official_website": "https://asana.com",
        "logo_url": "https://avatars.githubusercontent.com/u/477790",
        "description": "Official Asana MCP server enabling AI agents to manage tasks, projects, and workflows in Asana. Create tasks, update status, manage team assignments, and automate project management operations.",
        "primary_use_case": "Task and project management",
        "key_capabilities": "Task CRUD, project management, team assignments, status updates, search",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (Asana account required)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "200+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 82,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Aggregators & Multi-Tool ─────────────────────────────────────────
    {
        "mcp_name": "Pipedream MCP Server",
        "type": "Server",
        "category": "Aggregators",
        "subcategory": "Integration Platform",
        "company_creator": "Pipedream",
        "github_url": "https://github.com/PipedreamHQ/pipedream/tree/master/modelcontextprotocol",
        "official_website": "https://pipedream.com",
        "logo_url": "https://avatars.githubusercontent.com/u/42394785",
        "description": "Pipedream's MCP integration providing AI agents with access to 2,500+ APIs through 8,000+ prebuilt tools. Manage automations, connect to services, and build workflows across hundreds of SaaS platforms through a unified MCP interface.",
        "primary_use_case": "Multi-API integration and workflow automation",
        "key_capabilities": "2,500+ API integrations, workflow automation, event-driven triggers",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Freemium",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "8000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 90,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "MindsDB MCP Server",
        "type": "Server",
        "category": "Aggregators",
        "subcategory": "Data Integration Platform",
        "company_creator": "MindsDB",
        "github_url": "https://github.com/mindsdb/mindsdb",
        "official_website": "https://mindsdb.com",
        "logo_url": "https://avatars.githubusercontent.com/u/33522289",
        "description": "MindsDB MCP server that connects and unifies data across various platforms and databases through a single MCP interface. Enables AI agents to query multiple data sources using SQL, create ML models, and automate data pipelines.",
        "primary_use_case": "Unified data access and AI/ML operations",
        "key_capabilities": "Multi-database queries, ML model creation, data pipelines, 100+ integrations",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "GPL-3.0",
        "pricing": "Freemium",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "25000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 88,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
    {
        "mcp_name": "Anyquery MCP Server",
        "type": "Server",
        "category": "Aggregators",
        "subcategory": "Data Query Engine",
        "company_creator": "julien040",
        "github_url": "https://github.com/julien040/anyquery",
        "official_website": "https://anyquery.dev",
        "logo_url": "https://avatars.githubusercontent.com/u/30878830",
        "description": "Single-binary MCP server that lets AI agents query 40+ apps and databases using SQL. Connects to PostgreSQL, MySQL, SQLite-compatible databases and cloud services like Notion, Airtable, and GitHub through a unified SQL interface.",
        "primary_use_case": "Unified SQL queries across apps and databases",
        "key_capabilities": "SQL queries, 40+ app connectors, data export, local-first",
        "programming_language": "Go",
        "open_source": "Yes",
        "license": "AGPL-3.0",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "5000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 86,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── AI/ML ─────────────────────────────────────────────────────────────
    {
        "mcp_name": "Hugging Face MCP Server",
        "type": "Server",
        "category": "AI/ML",
        "subcategory": "Model Hub",
        "company_creator": "Hugging Face",
        "github_url": "https://github.com/huggingface/huggingface-mcp-server",
        "official_website": "https://huggingface.co",
        "logo_url": "https://huggingface.co/front/assets/huggingface_logo.svg",
        "description": "Official Hugging Face MCP server providing AI agents with access to the Hugging Face ecosystem. Search models, datasets, and Spaces; run inference on hosted models; manage repositories; and interact with the Hugging Face community.",
        "primary_use_case": "AI model and dataset discovery and inference",
        "key_capabilities": "Model search, inference API, dataset access, Spaces, repo management",
        "programming_language": "Python",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Freemium",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "500+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 87,
        "is_official": True,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Social Media ─────────────────────────────────────────────────────
    {
        "mcp_name": "Twitter/X MCP Server",
        "type": "Server",
        "category": "Social Media",
        "subcategory": "Social Networking",
        "company_creator": "Community (vidhupv)",
        "github_url": "https://github.com/vidhupv/x-mcp",
        "official_website": "https://x.com",
        "logo_url": "https://abs.twimg.com/responsive-web/client-web/icon-ios.77d25eba.png",
        "description": "MCP server for Twitter/X platform integration enabling AI agents to post tweets, search content, manage timelines, and interact with the Twitter/X API. Supports both reading and posting operations with OAuth authentication.",
        "primary_use_case": "Twitter/X social media management",
        "key_capabilities": "Tweet posting, search, timeline reading, user lookup, trends",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (Twitter API required)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "200+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 78,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Design ────────────────────────────────────────────────────────────
    {
        "mcp_name": "Figma MCP Server (Cursor)",
        "type": "Server",
        "category": "Architecture & Design",
        "subcategory": "UI/UX Design",
        "company_creator": "Figma (Sonnylazuardi)",
        "github_url": "https://github.com/nichochar/figma-mcp",
        "official_website": "https://www.figma.com",
        "logo_url": "https://avatars.githubusercontent.com/u/5155369",
        "description": "MCP server enabling AI agents to interact with Figma design files. Read design data, extract component information, access design tokens, and bridge the gap between design and code through Figma's REST API.",
        "primary_use_case": "Design-to-code workflows and Figma integration",
        "key_capabilities": "Read designs, extract components, design tokens, layout info",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free (Figma access required)",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "1000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 84,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Coding Agents ─────────────────────────────────────────────────────
    {
        "mcp_name": "Desktop Commander MCP",
        "type": "Server",
        "category": "Coding Agents",
        "subcategory": "IDE & File Management",
        "company_creator": "wonderwhy-er",
        "github_url": "https://github.com/wonderwhy-er/DesktopCommanderMCP",
        "official_website": "https://github.com/wonderwhy-er/DesktopCommanderMCP",
        "logo_url": "https://avatars.githubusercontent.com/u/1150644",
        "description": "Swiss-army-knife MCP server for AI coding agents that can manage and execute programs, read, write, search, and edit code and text files. Provides comprehensive local development capabilities for autonomous coding workflows.",
        "primary_use_case": "Comprehensive local development for AI agents",
        "key_capabilities": "File management, code editing, program execution, file search, text manipulation",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "2000+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 85,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },

    # ── Home Automation ───────────────────────────────────────────────────
    {
        "mcp_name": "Home Assistant MCP Server",
        "type": "Server",
        "category": "Home Automation",
        "subcategory": "Smart Home",
        "company_creator": "Community (jango-blockchained)",
        "github_url": "https://github.com/jango-blockchained/homeassistant-mcp",
        "official_website": "https://www.home-assistant.io",
        "logo_url": "https://avatars.githubusercontent.com/u/13844975",
        "description": "MCP server for Home Assistant smart home platform. Enables AI agents to control smart devices, query sensor states, trigger automations, and manage Home Assistant entities through the Home Assistant API.",
        "primary_use_case": "Smart home control and automation",
        "key_capabilities": "Device control, sensor queries, automation triggers, entity management",
        "programming_language": "TypeScript",
        "open_source": "Yes",
        "license": "MIT",
        "pricing": "Free",
        "supported_platforms": "macOS, Windows, Linux",
        "github_stars": "300+",
        "discovery_source": "awesome-mcp-servers",
        "quality_score": 80,
        "is_official": False,
        "active": "Yes",
        "last_verified": "2026-09-15",
    },
]


# ---------------------------------------------------------------------------
# CSV generation
# ---------------------------------------------------------------------------

CSV_COLUMNS = [
    "mcp_name",
    "type",
    "category",
    "subcategory",
    "company_creator",
    "official_website",
    "github_url",
    "logo_url",
    "description",
    "primary_use_case",
    "key_capabilities",
    "programming_language",
    "open_source",
    "license",
    "pricing",
    "supported_platforms",
    "github_stars",
    "active",
    "is_official",
    "discovery_source",
    "quality_score",
    "last_verified",
]


def write_csv(data: list[dict], output_path: str) -> None:
    """Write curated data to a CSV file."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for row in data:
            writer.writerow(row)
    print(f"✅ Wrote {len(data)} records to {output_path}")


def write_json(data: list[dict], output_path: str) -> None:
    """Write curated data to a JSON file."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False, default=str)
    print(f"✅ Wrote {len(data)} records to {output_path}")


def print_summary(data: list[dict]) -> None:
    """Print a summary of the extracted data."""
    print("\n" + "=" * 60)
    print("AIOrbit MCP Dataset — Extraction Summary")
    print("=" * 60)
    print(f"  Total records:    {len(data)}")

    categories = {}
    for r in data:
        cat = r.get("category", "Unknown")
        categories[cat] = categories.get(cat, 0) + 1
    print(f"  Categories:       {len(categories)}")

    official = sum(1 for r in data if r.get("is_official"))
    print(f"  Official servers: {official}")
    print(f"  Community:        {len(data) - official}")

    types = {}
    for r in data:
        t = r.get("type", "Unknown")
        types[t] = types.get(t, 0) + 1
    for t, count in sorted(types.items()):
        print(f"  Type {t}: {count}")

    scores = [r.get("quality_score", 0) for r in data]
    if scores:
        print(f"  Avg quality:      {sum(scores) / len(scores):.1f}")
        print(f"  Min quality:      {min(scores)}")
        print(f"  Max quality:      {max(scores)}")

    print("\n  Records by category:")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"    {cat}: {count}")

    print("=" * 60)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    final_dir = os.path.join(base_dir, "data", "final")

    # Remove duplicates by name
    seen = set()
    unique = []
    for r in CURATED_MCP_DATA:
        name = r["mcp_name"].lower().strip()
        if name not in seen:
            seen.add(name)
            unique.append(r)
        else:
            print(f"⚠️  Duplicate removed: {r['mcp_name']}")

    print_summary(unique)

    # Write outputs
    csv_path = os.path.join(final_dir, "mcp_dataset.csv")
    json_path = os.path.join(final_dir, "mcp_dataset.json")
    write_csv(unique, csv_path)
    write_json(unique, json_path)

    print(f"\n🎉 Dataset generation complete!")
    print(f"   CSV: {csv_path}")
    print(f"   JSON: {json_path}")


if __name__ == "__main__":
    main()
